[project]
name = "ranked-retrieval-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "spacy[transformers]>=3.8.7",
]
